version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: .
    depends_on:
      - database
      - cache     # <-- NOVO: A API agora também depende do cache
    environment:
      - DB_HOST=database
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=urldb
      - DB_PORT=5432
      - REDIS_HOST=cache    # <-- NOVO: Passando o host do Redis para a API
      - REDIS_PORT=6379   # <-- NOVO: Porta padrão do Redis

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=urldb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # NOVO SERVIÇO: Nosso cache em memória
  cache:
    image: redis:7-alpine # Usando a imagem oficial e leve do Redis
    restart: always       # É uma boa prática para um cache reiniciar automaticamente

volumes:
  postgres_data: {}