services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: .
    depends_on:
      - database
      - cache
    environment:
      - DB_HOST=database
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=urldb
      - DB_PORT=5432
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    # MUDANÇA: Não precisamos mais do driver de log aqui
    # Os logs serão coletados diretamente pelo Promtail

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=urldb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:7-alpine
    restart: always

  # --- NOVA STACK DE LOGGING ---
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000" # A porta do Grafana é a 3000
    depends_on:
      - loki

volumes:
  postgres_data: {}