version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: .
    depends_on:
      - database  # <-- MUDANÇA: Agora a API depende do banco de dados.
    environment:  # <-- NOVO: Variáveis de ambiente para a API se conectar ao banco.
      - DB_HOST=database
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=urldb
      - DB_PORT=5432

  # NOVO SERVIÇO: Nosso banco de dados PostgreSQL
  database:
    image: postgres:15-alpine # Usamos uma imagem oficial e leve do PostgreSQL.
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=urldb
    volumes:
      # Este é o segredo da persistência!
      # Mapeia o volume 'postgres_data' para a pasta onde o PostgreSQL guarda seus dados.
      - postgres_data:/var/lib/postgresql/data

# NOVO BLOCO: Declaramos o volume que será gerenciado pelo Docker.
volumes:
  postgres_data: {}