
services:
  nginx:
    # ... (sem mudanças aqui)
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: .
    depends_on:
      - database
      - cache
      - fluentd
    environment:
      # ... (sem mudanças aqui)
      - DB_HOST=database
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=urldb
      - DB_PORT=5432
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    # MUDANÇA IMPORTANTE: Dizendo ao Docker para enviar os logs deste serviço para o Fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: "app.nodejs.{{.ID}}" # Etiqueta para identificar os logs

  database:
    # ... (sem mudanças aqui)
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=urldb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    # ... (sem mudanças aqui)
    image: redis:7-alpine
    restart: always

  # --- NOVOS SERVIÇOS DE LOGGING ---
  fluentd:
    build: ./fluentd
    ports:
      - "24224:24224"       # Porta para receber logs
      - "24224:24224/udp"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:8.14.1 # Usando uma versão específica
    environment:
      - discovery.type=single-node # Essencial para rodar em um nó só
      - xpack.security.enabled=false # Desabilita login/senha para simplificar
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Limita o uso de memória
    volumes:
      - es_data:/usr/share/elasticsearch/data # Volume para persistir os dados do ES
    ports:
      - "9200:9200" # Porta da API do ES

  kibana:
    image: kibana:8.14.1 # A versão deve ser a mesma do Elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 # Diz ao Kibana onde encontrar o ES
    ports:
      - "5601:5601" # Porta da interface web do Kibana
    depends_on:
      - elasticsearch

volumes:
  postgres_data: {}
  es_data: {} # Declara o novo volume para os dados do Elasticsearch